# If this file is removed default config from firebase component will be used
# Due to API 36 mocked api tests failing, leaving client specific config as is.
mobileTest:
  timeout: 30m
  device:
  - model: MediumPhone.arm
    version: 34
  - model: MediumPhone.arm
    version: 26
smokeTest:
  timeout: 30m
  device:
  - model: shiba
    version: 34
tvTest:
  timeout: 30m
  device:
  - model: GoogleTvEmulator
    orientation: landscape
    version: 30
